version: "3.9"
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "sysadminEHU"
      MYSQL_DATABASE: "appDb"
    volumes:
      - ./appDb.sql:/docker-entrypoint-initdb.d/appDb.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 30s
      timeout: 5s
      retries: 20

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

  app:
    build: ./app
    image: sergiom8m8/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" 
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    depends_on:
      - api-db
      - api-emails

  api-db:
    build: ./api-db
    image: sergiom8m8/api-db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db

  api-emails:
    build: ./api-emails
    image: sergiom8m8/api-emails
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
 