version: '3'
services:

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" 
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - api_db
      - api_emails

  api_db: 
    build:
      context: ./API_db
      dockerfile: Dockerfile
    volumes:
      - ./API_db:/app
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db

  api_emails:
    build:
      context: ./API_emails
      dockerfile: Dockerfile
    volumes:
      - ./API_emails:/app

  db:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: sysadminEHU
      MYSQL_DATABASE: appDb
    volumes:
      - ./appDb.sql:/docker-entrypoint-initdb.d/appDb.sql
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"  
    depends_on:
      - db

volumes:
  mysql_data: