version: '3'
services:

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"  # Puedes acceder al dashboard de Traefik en http://localhost:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" 
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - api

  api: 
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - ./API:/app
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db

  db:
    image: mysql:latest  # Utiliza la imagen oficial de MySQL
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del contenedor MySQL al puerto 3306 del host
    environment:
      MYSQL_ROOT_PASSWORD: sysadminEHU
      MYSQL_DATABASE: appDb
    volumes:
      - ./appDb.sql:/docker-entrypoint-initdb.d/appDb.sql
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  # Configura el host de MySQL para phpMyAdmin
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"  # Mapea el puerto 8080 del host al puerto 80 de phpMyAdmin
    depends_on:
      - db

volumes:
  mysql_data: