apiVersion: apps/v1
kind: Deployment

metadata:
  name: phpmyadmin-deployment
  labels:
    component: phpmyadmin

spec:
  replicas: 1
  selector:
    matchLabels:
      component: phpmyadmin

  template:

    metadata:
      labels:
        component: phpmyadmin

    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 8081
          env:
            - name: PMA_HOST
              value: db
            - name: PMA_PORT
              value: "3306"

---

apiVersion: v1
kind: Service

metadata:
  name: phpmyadmin

spec:
  type: ClusterIP
  selector:
    component: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081